table fact_purchases
	lineageTag: b0000001-0000-0000-0000-000000000000

	measure 'Total Revenue' = SUM(fact_purchases[price])
		formatString: \$#,0.00
		displayFolder: 01 KPIs
		lineageTag: c0000001-0001-0000-0000-000000000000

	measure 'Total Players' = DISTINCTCOUNT(dim_players[player_id])
		formatString: #,0
		displayFolder: 01 KPIs
		lineageTag: c0000001-0002-0000-0000-000000000000

	measure 'Paying Players' = CALCULATE(DISTINCTCOUNT(dim_players[player_id]), dim_players[is_payer] = TRUE())
		formatString: #,0
		displayFolder: 01 KPIs
		lineageTag: c0000001-0003-0000-0000-000000000000

	measure 'Paying Rate %' = DIVIDE([Paying Players], [Total Players], 0)
		formatString: 0.0%
		displayFolder: 01 KPIs
		lineageTag: c0000001-0004-0000-0000-000000000000

	measure 'ARPU (All Players)' = DIVIDE([Total Revenue], DISTINCTCOUNT(dim_players[player_id]))
		formatString: \$#,0.00
		displayFolder: 01 KPIs
		lineageTag: c0000001-0005-0000-0000-000000000000

	measure 'ARPPU (Paying Players Only)' = DIVIDE([Total Revenue], CALCULATE(DISTINCTCOUNT(dim_players[player_id]), dim_players[is_payer] = TRUE()))
		formatString: \$#,0.00
		displayFolder: 01 KPIs
		lineageTag: c0000001-0006-0000-0000-000000000000

	measure 'Cart Items Abandoned' = COUNTROWS(fact_abandoned_carts)
		formatString: #,0
		displayFolder: 02 Abandonment
		lineageTag: c0000001-0007-0000-0000-000000000000

	measure 'Cart Items Total' = [Cart Items Abandoned] + COUNTROWS(fact_purchases)
		formatString: #,0
		displayFolder: 02 Abandonment
		lineageTag: c0000001-0008-0000-0000-000000000000

	measure 'Cart Abandonment Rate %' = DIVIDE([Cart Items Abandoned], [Cart Items Total], 0)
		formatString: 0.0%
		displayFolder: 02 Abandonment
		lineageTag: c0000001-0009-0000-0000-000000000000

	measure 'Lost Revenue (Abandoned $)' = SUM(fact_abandoned_carts[price])
		formatString: \$#,0.00
		displayFolder: 02 Abandonment
		lineageTag: c0000001-000a-0000-0000-000000000000

	measure 'Recoverable Revenue ($)' = [Lost Revenue (Abandoned $)] * [First-Purchase Conversion Rate %]
		formatString: \$#,0.00
		displayFolder: 02 Abandonment
		lineageTag: c0000001-000b-0000-0000-000000000000

	measure 'Crate Keys' = CALCULATE([Total Revenue], fact_purchases[category] = "Crate keys")
		formatString: \$#,0.00
		displayFolder: 03 Revenue by Category
		lineageTag: c0000001-000c-0000-0000-000000000000

	measure Ranks = CALCULATE([Total Revenue], fact_purchases[category] = "Ranks")
		formatString: \$#,0.00
		displayFolder: 03 Revenue by Category
		lineageTag: c0000001-000d-0000-0000-000000000000

	measure Perks = CALCULATE([Total Revenue], fact_purchases[category] = "Perks")
		formatString: \$#,0.00
		displayFolder: 03 Revenue by Category
		lineageTag: c0000001-000e-0000-0000-000000000000

	measure Sellwands = CALCULATE([Total Revenue], fact_purchases[category] = "Sellwands")
		formatString: \$#,0.00
		displayFolder: 03 Revenue by Category
		lineageTag: c0000001-000f-0000-0000-000000000000

	measure 'Top Category by Revenue' =
			VAR Ranked = ADDCOLUMNS(VALUES(fact_purchases[category]), "@Rev", [Total Revenue])
			VAR TopRow = TOPN(1, Ranked, [@Rev], DESC)
			RETURN CONCATENATEX(TopRow, fact_purchases[category] & " ($" & FORMAT([@Rev], "#,0") & ")")
		displayFolder: 03 Revenue by Category
		lineageTag: c0000001-0010-0000-0000-000000000000

	measure 'Default Players (Visited Store)' = CALCULATE(DISTINCTCOUNT(dim_players[player_id]), dim_players[rank] = "Default", dim_players[webstore_visits] > 0)
		formatString: #,0
		displayFolder: 04 Conversion
		lineageTag: c0000001-0011-0000-0000-000000000000

	measure 'Default Players (Converted)' = CALCULATE(DISTINCTCOUNT(dim_players[player_id]), dim_players[rank] = "Default", dim_players[total_transactions] >= 1)
		formatString: #,0
		displayFolder: 04 Conversion
		lineageTag: c0000001-0012-0000-0000-000000000000

	measure 'First-Purchase Conversion Rate %' = DIVIDE([Default Players (Converted)], [Default Players (Visited Store)], 0)
		formatString: 0.0%
		displayFolder: 04 Conversion
		lineageTag: c0000001-0013-0000-0000-000000000000

	measure 'Avg Playtime (Hours)' = AVERAGE(dim_players[total_playtime_hours])
		formatString: #,0.0
		displayFolder: 05 Engagement
		lineageTag: c0000001-0014-0000-0000-000000000000

	measure 'Whale Threshold ($)' = PERCENTILEX.INC(FILTER(dim_players, dim_players[is_payer] = TRUE()), dim_players[total_spent_dollars], 0.9)
		formatString: \$#,0.00
		displayFolder: 05 Engagement
		lineageTag: c0000001-0015-0000-0000-000000000000

	measure 'Whale Revenue Share %' =
			VAR Threshold = [Whale Threshold ($)]
			VAR WhaleRev = CALCULATE([Total Revenue], FILTER(dim_players, dim_players[total_spent_dollars] >= Threshold))
			RETURN DIVIDE(WhaleRev, [Total Revenue], 0)
		formatString: 0.0%
		displayFolder: 05 Engagement
		lineageTag: c0000001-0016-0000-0000-000000000000

	column purchase_key
		dataType: int64
		formatString: 0
		lineageTag: b0000001-0001-0000-0000-000000000000
		summarizeBy: none
		sourceColumn: purchase_key

		annotation SummarizationSetBy = Automatic

	column player_id
		dataType: int64
		formatString: 0
		lineageTag: b0000001-0002-0000-0000-000000000000
		summarizeBy: none
		sourceColumn: player_id

		annotation SummarizationSetBy = Automatic

	column username
		dataType: string
		lineageTag: b0000001-0003-0000-0000-000000000000
		summarizeBy: none
		sourceColumn: username

		annotation SummarizationSetBy = Automatic

	column rank
		dataType: string
		lineageTag: b0000001-0004-0000-0000-000000000000
		summarizeBy: none
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: b0000001-0005-0000-0000-000000000000
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		formatString: \$#,0.00
		lineageTag: b0000001-0006-0000-0000-000000000000
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: b0000001-0007-0000-0000-000000000000
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	partition fact_purchases = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\danie\PycharmProjects\CustomerBehaviour\fact_purchases.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"purchase_key", Int64.Type}, {"player_id", Int64.Type}, {"username", type text}, {"rank", type text}, {"item", type text}, {"price", type number}, {"category", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

